---
all:
  hosts:
     ec2-44-211-157-180.compute-1.amazonaws.com:
       ansible_user: ec2-user
       ansible_python_interpreter: /usr/bin/python3
       ansible_ssh_private_key_file: /Users/taylorgrafft/Desktop/Auburn Comp Sci/Cloud Computing/pair.pem 
     ec2-54-91-30-245.compute-1.amazonaws.com:
       ansible_user: ec2-user
       ansible_python_interpreter: /usr/bin/python3
       ansible_ssh_private_key_file: /Users/taylorgrafft/Desktop/Auburn Comp Sci/Cloud Computing/pair.pem
     ec2-3-210-88-212.compute-1.amazonaws.com:
       ansible_user: ec2-user
       ansible_python_interpreter: /usr/bin/python3
       ansible_ssh_private_key_file: /Users/taylorgrafft/Desktop/Auburn Comp Sci/Cloud Computing/pair.pem
  children:
     al2023:
       hosts:
          ec2-44-211-157-180.compute-1.amazonaws.com:
          ec2-54-91-30-245.compute-1.amazonaws.com:
          ec2-3-210-88-212.compute-1.amazonaws.com:
